# ================
# SOFTWARE LICENSE
# ================

# The MIT License (MIT)

# Copyright (c) 2020 Yutaka Sawai (Varipon)

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# ==============================================================
# LICENSE FOR CONTENT PROCEDURALLY GENERATED USING THIS SOFTWARE
# ==============================================================

# All content procedurally generated by this software and its permutations
# are licensed under Creative Commons Attribution By 3.0:

# https://creativecommons.org/licenses/by/3.0/


#!/usr/bin/python

import bpy
from bpy import *

import mathutils
import math
from mathutils import *
from math import *


class Formula:

    def __init__(self, P, A, J, move, part, helicity, start, end):

        global interval
        global frame_start
        global frame_end

        self.interval = interval
        self.frame_start = frame_start
        self.frame_end = frame_end

        # pivot factor
        self.P = P

        # scale factor
        self.A = A 
        
        # joint number
        self.J = J

        # name
        self.move = move

        # element
        self.part = part

        # element helicity
        self.helicity = helicity

        self.start = start
        self.end = end

        # Create armature and object
        self.amt = bpy.data.armatures.new(move + '.' + part + '.' + helicity + '.data')
        self.rig = bpy.data.objects.new(move + '.' + part + '.' + helicity, self.amt)

        # Joints α(n) -> a[n], β(n) -> b[n], γ(n) -> y[n], δ(n) -> o[n]
        self.a = [0 for i in range(4)] # Joint α
        self.b = [0 for i in range(self.J)] # Joint β
        self.y = [0 for i in range(self.J)] # Joint γ
        self.o = [0 for i in range(self.J)] # Joint δ

        # Configuration Movement
        self.configMovement(self.P, self.A, self.J, self.a, self.b, self.y, self.o)

        # Construction Movement
        self.constructMovement(self.J, self.helicity, self.amt, self.rig, self.a, self.b, self.y, self.o)

        # Construction Rotation
        self.configRotation(self.rig, self.interval, self.frame_start, self.frame_end, self.start, self.end)

        # Configuration Linkage
        self.configLink(self.A, self.J, self.helicity, self.rig, self.move, self.part)

        # Construction Linkage
        self.constructLink(self.A, self.J, self.helicity, self.rig, self.move, self.part)


    def configMovement(self, P, A, J, a, b, y, o):

        mat_a = [0 for i in range(4)] # Joint α matrix
        mat_b = [0 for i in range(self.J)] # Joint β matrix
        mat_y = [0 for i in range(self.J)] # Joint γ matrix
        mat_o = [0 for i in range(self.J)] # Joint δ matrix

        a[1] = mathutils.Euler((P, A, 0.0), 'XYZ')
        print ("a1 =", a[1])

        a[2] = mathutils.Euler((A, -A, 0.0), 'XYZ')
        print ("a2 =", a[2])

        b[1] = mathutils.Euler((-A, A, 0.0), 'XYZ')
        print ("b1 =", b[1])

        o[1] = mathutils.Euler((A, A, 0.0), 'XYZ')
        print ("o1 =", o[1])

        B = A * 2 * sqrt (2)
        C = B + (B * sqrt (2))
        D = C * sqrt (2)
        E = C + D

        a[0] = mathutils.Euler((-A - E + (D * 0.5), -A - (D * 0.5), 0.0), 'XYZ')
        print ("a0 =", a[0])
        mat_a[0] = Matrix.Translation(a[0])

        a[3] = mathutils.Euler((0-a[0].x, 0-a[0].y, 0-a[0].z), 'XYZ')
        print ("a3 =", a[3])
        mat_a[3] = Matrix.Translation(a[3]) 

        y[1] = mathutils.Euler((-A, -A, 0.0), 'XYZ')
        print ("y1 =", y[1])
        mat_y[1] = Matrix.Translation(y[1])

### pattern A

        b[2] = mathutils.Euler((a[0].x + E + (A * 2), a[0].y + (A * 2), 0.0), 'XYZ')
        print ("b2 =", b[2])
        mat_b[2] = Matrix.Translation(b[2])

        b[3] = mathutils.Euler((a[0].x + E - (D * 0.5), a[0].y - (A * 2), 0.0), 'XYZ')
        print ("b3 =", b[3])
        mat_b[3] = Matrix.Translation(b[3])
        
        y[2] = mathutils.Euler((a[0].x + E, a[0].y, 0.0), 'XYZ')
        print ("y2 =", y[2])
        mat_y[2] = Matrix.Translation(y[2])

        y[3] = mathutils.Euler((a[0].x + E - (D * 0.5), a[0].y - (D * 0.5), 0.0), 'XYZ')
        print ("y3 =", y[3])
        mat_y[3] = Matrix.Translation(y[3])

        o[2] = mathutils.Euler((a[0].x + E + (A * 2), a[0].y - (A * 2), 0.0), 'XYZ')
        print ("o2 =", o[2])
        mat_o[2] = Matrix.Translation(o[2])
        
        o[3] = mathutils.Euler((a[0].x + E - (D * 0.5) - (A * 2), a[0].y - (D * 0.5) - (A * 2), 0.0), 'XYZ')
        print ("o3 =", o[3])
        mat_o[3] = Matrix.Translation(o[3])

### pattern A end

        org_rot_mat = Matrix.Rotation(math.radians(0), 4, 'Z')

        # define the rotation
        rot_mat = Matrix.Rotation(math.radians(-45), 4, 'Z')   

        for j in range(2, J - 2):

            mat_y[j + 2] = mat_a[0] @ org_rot_mat @ rot_mat @ mat_a[3] @ mat_y[j]

#            obj.matrix_world = mat_y[j + 2]
            # extract components back out of the matrix
            loc, rot, sca = mat_y[j + 2].decompose()
            y[j + 2] = mathutils.Euler(loc, 'XYZ')
            print("y"+str(j + 2)+" = ", y[j + 2], rot, sca)

            mat_b[j + 2] = mat_a[0] @ org_rot_mat @ rot_mat @ mat_a[3] @ mat_b[j]
            
#            obj.matrix_world = mat_b[j + 2]
            # extract components back out of the matrix
            loc, rot, sca = mat_b[j + 2].decompose()
            b[j + 2] = mathutils.Euler(loc, 'XYZ')
            print("b"+str(j + 2)+" = ", b[j + 2], rot, sca)

            mat_o[j + 2] = mat_a[0] @ org_rot_mat @ rot_mat @ mat_a[3] @ mat_o[j]
            
#            obj.matrix_world = mat_o[j + 2]
            # extract components back out of the matrix
            loc, rot, sca = mat_o[j + 2].decompose()
            o[j + 2] = mathutils.Euler(loc, 'XYZ')
            print("o"+str(j + 2)+" = ", o[j + 2], rot, sca)


    def constructMovement(self, J, helicity, amt, rig, a, b, y, o):

        # Linkages
        aa = [[0 for i in range(4)] for j in range(4)] # Link α(i) - α(j)
        ab = [[0 for i in range(4)] for j in range(4)] # Link α(i) - β(j)
        ya = [[0 for i in range(4)] for j in range(4)] # Link γ(i) - α(j)
        ao = [[0 for i in range(4)] for j in range(4)] # Link α(i) - δ(j)
        ob = [[0 for i in range(self.J)] for j in range(self.J)] # Link δ(i) - β(j)
        yy = [[0 for i in range(self.J)] for j in range(self.J)] # Link γ(i) - γ(j)
        by = [[0 for i in range(self.J)] for j in range(self.J)] # Link β(i) - γ(j)
        yo = [[0 for i in range(self.J)] for j in range(self.J)] # Link γ(i) - δ(j)

        rig.location = mathutils.Euler((0.0, 0.0, 0.0), 'XYZ')
        rig.show_in_front = True
        amt.show_names = True
        amt.display_type = 'STICK'
#        amt.display_type = 'BBONE'

        # Link object to scene

        bpy.data.collections['movement'].objects.link(rig)
        bpy.context.view_layer.objects.active = rig
        bpy.context.view_layer.update()

        # Edit
        bpy.ops.object.editmode_toggle()

        # Construction Linkage
        aa[2][1] = amt.edit_bones.new('a2a1')
        aa[2][1].head = a[2]
        aa[2][1].tail = a[1]
        
        ab[1][1] = amt.edit_bones.new('a1b1')
        ab[1][1].head = a[1]
        ab[1][1].tail = b[1]
        ab[1][1].parent = aa[2][1]
 
        by[1][1] = amt.edit_bones.new('b1y1')
        by[1][1].head = b[1]
        by[1][1].tail = y[1]
        by[1][1].parent = ab[1][1]
        by[1][1].use_inherit_rotation = False

        ya[1][2] = amt.edit_bones.new('y1a2')
        ya[1][2].head = y[1]
        ya[1][2].tail = a[2]
        ya[1][2].parent = by[1][1]

        ao[2][1] = amt.edit_bones.new('a2o1')
        ao[2][1].head = a[2]
        ao[2][1].tail = o[1]
        ao[2][1].parent = ya[1][2]

        ob[1][2] = amt.edit_bones.new('o1b2')
        ob[1][2].head = o[1]
        ob[1][2].tail = b[2]
        ob[1][2].parent = ao[2][1]
        
        yy[1][2] = amt.edit_bones.new('y1y2')
        yy[1][2].head = y[1]
        yy[1][2].tail = y[2]
        yy[1][2].parent = by[1][1]

        for j in range(2, J - 1):

            by[j][j] = amt.edit_bones.new('b'+ str(j) + 'y'+ str(j))
            by[j][j].head = b[j]
            by[j][j].tail = y[j]
            by[j][j].parent = ob[j-1][j]

            yo[j][j] = amt.edit_bones.new('y'+ str(j) + 'o'+ str(j))
            yo[j][j].head = y[j]
            yo[j][j].tail = o[j]
            yo[j][j].parent = yy[j-1][j]

            yy[j][j+1] = amt.edit_bones.new('y'+ str(j) + 'y'+ str(j+1))
            yy[j][j+1].head = y[j]
            yy[j][j+1].tail = y[j+1]
            yy[j][j+1].parent = by[j][j]

            if j < (J-2):
                ob[j][j+1] = amt.edit_bones.new('o'+ str(j) + 'b'+ str(j+1))
                ob[j][j+1].head = o[j]
                ob[j][j+1].tail = b[j+1]
                ob[j][j+1].parent = yo[j][j]

        # all bones select

        # Bone constraints. Armature must be in pose mode.
        bpy.ops.object.mode_set(mode='POSE')

        bpy.ops.pose.select_all(action="SELECT")

        # Edit
        bpy.ops.object.editmode_toggle()

        if helicity == 'right':
            bpy.ops.armature.calculate_roll(type='GLOBAL_POS_Z')
        else:
            bpy.ops.armature.calculate_roll(type='GLOBAL_NEG_Z')
 
        # IK constraint
        cns = rig.pose.bones['y1a2'].constraints.new('IK')
        cns.name = 'Ik'
        cns.target = rig
        cns.subtarget = 'a2a1'
        cns.chain_count = 2
        cns.use_stretch = False

        for j in range(2, J - 1):
            cns = rig.pose.bones['b'+str(j) +'y'+str(j)].constraints.new('IK')
            cns.name = 'Ik'
            cns.target = rig
            cns.subtarget = 'y'+str(j)+'o'+str(j)
            cns.iterations = 500
            cns.chain_count = 2
            cns.use_stretch = False

        bpy.ops.object.mode_set(mode='OBJECT')
        

    def configRotation(self, rig, interval, frame_start, frame_end, start, end):

        # Bone constraints. Armature must be in pose mode.
        bpy.ops.object.mode_set(mode='POSE')

        # key insert 
        keyframe_insert_interval = interval

        rig.pose.bones["a1b1"].rotation_mode = 'XYZ'
        rig.pose.bones["a1b1"].rotation_euler.z = math.radians(start) 
        rig.pose.bones["a1b1"].keyframe_insert(data_path="rotation_euler",frame=frame_start)

        rig.pose.bones["a1b1"].rotation_mode = 'XYZ'
        rig.pose.bones["a1b1"].rotation_euler.z = math.radians(end)
        rig.pose.bones["a1b1"].keyframe_insert(data_path="rotation_euler",frame=frame_end)

        for curve in bpy.context.active_object.animation_data.action.fcurves:
            cycles = curve.modifiers.new(type='CYCLES')
            cycles.mode_before = 'REPEAT_OFFSET'
            cycles.mode_after = 'REPEAT_OFFSET'

            for keyframe in curve.keyframe_points:
                keyframe.interpolation = 'LINEAR'

        bpy.ops.object.mode_set(mode='OBJECT')


    def configLink(self, A, J, helicity, rig, move, part):

        bpy.ops.object.mode_set(mode='OBJECT')
    
        Q = (0.18648+0.146446)*A
    #   Z = -Q*2
        Z = 0.0

        obj_joint = bpy.data.objects["joint.gold.000"].copy()
        obj_joint.location = (0.0, 0.0, -Q*3+Z)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "a2a1.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        obj_joint = bpy.data.objects["joint.silver.001"].copy()
        obj_joint.location = (0.0, 0.0, +Q+Z)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "y1a2.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        obj_joint = bpy.data.objects["joint.copper.001"].copy()
        obj_joint.location = (0.0, 0.0, +Q*3+Z)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "a2o1.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        obj_joint = bpy.data.objects["joint.blue.001"].copy()
        obj_joint.location = (0.0, 0.0, -Q*2+Z)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "a1b1.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)


        for n in range(1, J - 1):

            if n <= (J-2):

                # Pattern 2 of by
                obj_joint = bpy.data.objects["joint.green.001"].copy()
                obj_joint.location = (0.0, 0.0, -Q + Q*((n+1) % 2)*4 +Z)
                obj_joint.scale = (A, A, A)
                obj_joint.name = "b"+str(n)+"y"+str(n)+".mesh." + move + '.' + part +'.' + helicity
                bpy.data.collections['link'].objects.link(obj_joint)

                # Pattern 2 of yy
                obj_joint = bpy.data.objects["joint.gold.00"+str(1 + (n+1) % 2)].copy()
                obj_joint.location = (0.0, 0.0, +Q*(1 - (n % 2))*2+Z)
                obj_joint.scale = (A, A, A)
                obj_joint.name = "y"+str(n)+"y"+str(n+1)+".mesh." + move + '.' + part +'.' + helicity
                bpy.data.collections['link'].objects.link(obj_joint)


            if n <= (J-3):

                # Pattern 1 of ob
                obj_joint = bpy.data.objects["joint.blue.001"].copy()
                obj_joint.location = (0.0, 0.0, -Q*2 + Q*(n % 2)*6 +Z)
                obj_joint.scale = (A, A, A)
                obj_joint.name = "o"+str(n)+"b"+str(n+1)+".mesh." + move + '.' + part +'.' + helicity
                bpy.data.collections['link'].objects.link(obj_joint)

                # Pattern 2 of yo
                obj_joint = bpy.data.objects["joint.copper.001"].copy()
                obj_joint.location = (0.0, 0.0, -Q + Q*((n+1) % 2)*4 +Z)
                obj_joint.scale = (A, A, A)
                obj_joint.name = "y"+str(n+1)+"o"+str(n+1)+".mesh." + move + '.' + part +'.' + helicity
                bpy.data.collections['link'].objects.link(obj_joint)


        for ob in data.collections['link'].objects:
            if "mesh" in ob.name:
                ob.select_set(state = True, view_layer = None)

        bpy.ops.object.make_single_user(type='SELECTED_OBJECTS', object=True, obdata=True, material=True, animation=True)
        bpy.context.scene.cursor.location = (0.0, 0.0, 0.0)
        bpy.ops.object.origin_set(type='ORIGIN_CURSOR')


    def constructLink(self, A, J, helicity, rig, move, part):

        # Move and rotate the tip bone in pose mode
        bpy.context.view_layer.objects.active = rig 

        Y = 1.1838*A

        for n in rig.pose.bones:
            if n.name != "o" + str(J-2) + "b" + str(J-1):
                # we can get the object from the pose bone
                obj = n.id_data
                matrix_final = obj.matrix_world @ n.matrix

                # Create armature and object
                lnk = bpy.data.armatures.new(n.name[:len(n.name)]+'.data.' + helicity)
                lnk_rig = bpy.data.objects.new(n.name[:len(n.name)]+'.link.' + helicity, lnk)
                lnk_rig.location = mathutils.Euler((0.0, 0.0, 0.0), 'XYZ')

                # rig.show_in_front = True
                lnk.show_names = True
                lnk.display_type = 'STICK'

                bpy.data.collections['link'].objects.link(lnk_rig)
                bpy.context.view_layer.objects.active = lnk_rig
                bpy.context.view_layer.update()

                # Create bones

                # mode='EDIT'
                bpy.ops.object.editmode_toggle()
    
                link = lnk.edit_bones.new(n.name[:len(n.name)])
                link.head = (0.0, 0.0, 0.0)
                link.tail = (0.0, Y, 0.0)

                link_head = lnk.edit_bones.new('head')
                link_head.head = (0.0, 0.0, 0.1)
                link_head.tail = (0.0, 0.0, 0.0)
                link_head.parent = link
                link_head.use_inherit_scale = False

                link_tail = lnk.edit_bones.new('tail')
                link_tail.head = (0.0, Y, 0.0)
                link_tail.tail = (0.0, Y, -0.1)
                link_tail.parent = link
                link_tail.use_inherit_scale = False

                bpy.ops.object.mode_set(mode='OBJECT')

                ob = bpy.data.objects[n.name[:len(n.name)]+'.mesh.' + move + '.' + part +'.' + helicity]
                ob.location = mathutils.Euler((0.0, 0.0, 0.0), 'XYZ')
    
                # Give mesh object an armature modifier, using vertex groups but
                # not envelopes
                mod = ob.modifiers.new('MyRigModif', 'ARMATURE')
                mod.object = lnk_rig
                mod.use_bone_envelopes = False
                mod.use_vertex_groups = True

                # Bone constraints. Armature must be in pose mode.
                bpy.ops.object.mode_set(mode='POSE')
 
                # Copy rotation constraints Base -> Tip
                pBase = lnk_rig.pose.bones[n.name[:len(n.name)]]
                cns = pBase.constraints.new('COPY_LOCATION')
                cns.name = 'Copy_Location'
                cns.target = rig
                cns.subtarget = n.name[:len(n.name)]
                cns.owner_space = 'WORLD'
                cns.target_space = 'WORLD'

                # Copy rotation constraints Base -> Tip
                pBase = lnk_rig.pose.bones[n.name[:len(n.name)]]
                cns = pBase.constraints.new('COPY_ROTATION')
                cns.name = 'Copy_Rotation'
                cns.target = rig
                cns.subtarget = n.name[:len(n.name)]
                cns.owner_space = 'WORLD'
                cns.target_space = 'WORLD'

                # StretchTo constraint Mid -> Tip with influence 0.5
                cns1 = pBase.constraints.new('STRETCH_TO')
                cns1.name = 'Stretch'
                cns1.target = rig
                cns1.subtarget = n.name[:len(n.name)]
                cns1.head_tail = 1
                cns1.rest_length = Y
                cns1.influence = 1
                cns1.keep_axis = 'PLANE_Z'
                cns1.volume = 'NO_VOLUME'

                bpy.ops.object.mode_set(mode='OBJECT')


class Finger(Formula):
    
    J = 6 #joint number

    # Overriding
    def __init__(self, P, A, move, part, helicity, start, end, y2, y3, y4, y5):

        global interval
        global frame_start
        global frame_end

        self.interval = interval
        self.frame_start = frame_start
        self.frame_end = frame_end
 
        # pivot factor
        self.P = P

        # scale factor
        self.A = A 

        # name
        self.move = move

        # element
        self.part = part

        # element helicity
        self.helicity = helicity

        self.start = start
        self.end = end
        
        # phalanx length
        self.y2 = y2
        self.y3 = y3
        self.y4 = y4
        self.y5 = y5

        # Create armature and object
        self.amt = bpy.data.armatures.new(move + '.' + part + '.' + helicity + '.data')
        self.rig = bpy.data.objects.new(move + '.' + part + '.' + helicity, self.amt)

        # Joints
        self.a = [0 for i in range(4)] # Joint α
        self.b = [0 for i in range(self.J)] # Joint β
        self.y = [0 for i in range(self.J)] # Joint γ
        self.o = [0 for i in range(self.J)] # Joint δ

        # Configuration Movement
        self.configMovement(self.P, self.A, self.J, self.a, self.b, self.y, self.o,
            self.y2, self.y3, self.y4, self.y5)

        # Construction Movement
        self.constructMovement(self.J, self.helicity, self.amt, self.rig, self.a, self.b, self.y, self.o)

        # Construction Rotation
        self.configRotation(self.rig, self.interval, self.frame_start, self.frame_end, self.start, self.end)

        # Configuration Linkage
        self.configLink(self.A, self.J, self.helicity, self.rig, self.move, self.part)

        # Construction Linkage
        self.constructLink(self.A, self.J, self.helicity, self.rig, self.move, self.part)


    # Overriding Configuration Movement
    def configMovement(self, P, A, J, a, b, y, o, y2, y3, y4, y5):
        
        a[1] = mathutils.Euler((P, A, 0.0), 'XYZ')
        print ("a1 =", a[1])

        a[2] = mathutils.Euler((A, -A, 0.0), 'XYZ')
        print ("a2 =", a[2])

        b[1] = mathutils.Euler((-A, A, 0.0), 'XYZ')
        print ("b1 =", b[1])

        o[1] = mathutils.Euler((A, A, 0.0), 'XYZ')
        print ("o1 =", o[1])

        B = A * 2 * sqrt (2)
        C = B + (B * sqrt (2))
        D = C * sqrt (2)
        E = C + D

        y[1] = mathutils.Euler((-A, -A, 0.0), 'XYZ')
        print ("y1 =", y[1])

        y[2] = y2
        print ("y2 =", y[2])

        y[3] = y3
        print ("y3 =", y[3])

        y[4] = y4
        print ("y4 =", y[4])

        y[5] = y5
        print ("y5 =", y[5])


        b[2] = mathutils.Euler((y[2].x+0.10012, y[2].y+0.170067, 0.0), 'XYZ')
        print ("b2 =", b[2])

        b[3] = mathutils.Euler((y[3].x-0.12471, y[3].y-0.03395, 0.0), 'XYZ')
        print ("b3 =", b[3])
        
        b[4] = mathutils.Euler((y[4].x-0.11426, y[4].y-0.03342, 0.0), 'XYZ')
        print ("b4 =", b[4])


        o[2] = mathutils.Euler((y[2].x+0.09016, y[2].y+0.142795, 0.0), 'XYZ')
        print ("o2 =", o[2])
        
        o[3] = mathutils.Euler((y[3].x+0.07367, y[3].y+0.09711, 0.0), 'XYZ')
        print ("o3 =", o[3])

        o[4] = mathutils.Euler((y[4].x+0.00899, y[4].y+0.03297, 0.0), 'XYZ')
        print ("o4 =", o[4])
        
        
class Wrist(Formula):

    J = 3 #joint number

    # Overriding
    def __init__(self, P, A, move, part, helicity, start, end, 
        disciple_loc, disciple_rot, disciple):

        global interval
        global frame_start
        global frame_end

        self.interval = interval
        self.frame_start = frame_start
        self.frame_end = frame_end

        # pivot factor
        self.P = P

        # scale factor
        self.A = A 

        # name
        self.move = move

        # element
        self.part = part

        # element helicity
        self.helicity = helicity

        self.start = start
        self.end = end

        # disciple position
        self.disciple_loc = disciple_loc
        self.disciple_rot = disciple_rot

        # disciple
        self.disciple = disciple

        # Create armature and object
        self.amt = bpy.data.armatures.new(move + '.' + part + '.' + helicity + '.data')
        self.rig = bpy.data.objects.new(move + '.' + part + '.' + helicity, self.amt)

        # Joints
        self.a = [0 for i in range(self.J)] # Joint α
        self.b = [0 for i in range(self.J)] # Joint β
        self.y = [0 for i in range(self.J)] # Joint γ
        self.o = [0 for i in range(self.J)] # Joint δ

        # Configuration Movement
        self.configMovement(self.P, self.A, self.J, self.a, self.b, self.y, self.o)

        # Construction Movement
        self.constructMovement(self.J, self.helicity, self.amt, self.rig, self.a, self.b, self.y, self.o)

        # Parent set disciple to master        
        self.setParent(self.helicity, self.move, self.rig, 
            self.disciple_loc, self.disciple_rot, self.disciple)

        # Construction Rotation
        self.configRotation(self.rig, self.interval, self.frame_start, self.frame_end, self.start, self.end)

        # Configuration Linkage
        self.configLink(self.A*0.3, self.J, self.helicity, self.rig, self.move, self.part)

        # Construction Linkage
        self.constructLink(self.A*0.3, self.J, self.helicity, self.rig, self.move, self.part)

    # Overriding Configuration Movement
    def configMovement(self, P, A, J, a, b, y, o):

        a[1] = mathutils.Euler((P, A, 0.0), 'XYZ')
        print ("a1 =", a[1])

        a[2] = mathutils.Euler((A, -A, 0.0), 'XYZ')
        print ("a2 =", a[2])

        b[1] = mathutils.Euler((-A, A, 0.0), 'XYZ')
        print ("b1 =", b[1])

        B = A * 2 * sqrt (2)
        C = B + (B * sqrt (2))
        D = C * sqrt (2)
        E = C + D

        y[1] = mathutils.Euler((-A, -A, 0.0), 'XYZ')
        print ("y1 =", y[1])
        
        y[2] = mathutils.Euler((-A, -(0.173028/0.351)*A, 0.0), 'XYZ')
        print ("y2 =", y[2])

        o[1] = mathutils.Euler((-A, (-5.09454/0.351)*A, 0.0), 'XYZ')
        print ("o1 =", o[1])

    def constructMovement(self, J, helicity, amt, rig, a, b, y, o):

        # Linkages
        aa = [[0 for i in range(4)] for j in range(4)] # Link α(i) - α(j)
        ab = [[0 for i in range(4)] for j in range(4)] # Link α(i) - β(j)
        ya = [[0 for i in range(4)] for j in range(4)] # Link γ(i) - α(j)
        yy = [[0 for i in range(self.J)] for j in range(self.J)] # Link γ(i) - γ(j)
        by = [[0 for i in range(self.J)] for j in range(self.J)] # Link β(i) - γ(j)
        yo = [[0 for i in range(self.J)] for j in range(self.J)] # Link γ(i) - δ(j)

        rig.location = mathutils.Euler((0.0, 0.0, 0.0), 'XYZ')
        rig.show_in_front = True
        amt.show_names = True
        amt.display_type = 'STICK'
#        amt.display_type = 'BBONE'

        # Link object to scene

        bpy.data.collections['movement'].objects.link(rig)
        bpy.context.view_layer.objects.active = rig
        bpy.context.view_layer.update()

        # Edit
        bpy.ops.object.editmode_toggle()

        # Construction Linkage
        aa[2][1] = amt.edit_bones.new('a2a1')
        aa[2][1].head = a[2]
        aa[2][1].tail = a[1]
        
        ab[1][1] = amt.edit_bones.new('a1b1')
        ab[1][1].head = a[1]
        ab[1][1].tail = b[1]
        ab[1][1].parent = aa[2][1]
 
        by[1][1] = amt.edit_bones.new('b1y1')
        by[1][1].head = b[1]
        by[1][1].tail = y[1]
        by[1][1].parent = ab[1][1]
        by[1][1].use_inherit_rotation = False

        ya[1][2] = amt.edit_bones.new('y1a2')
        ya[1][2].head = y[1]
        ya[1][2].tail = a[2]
        ya[1][2].parent = by[1][1]

        yo[1][1] = amt.edit_bones.new('y1o1')
        yo[1][1].head = y[1]
        yo[1][1].tail = o[1]
        yo[1][1].parent = by[1][1]
   
        yy[1][2] = amt.edit_bones.new('y1y2')
        yy[1][2].head = y[1]
        yy[1][2].tail = y[2]
        yy[1][2].parent = by[1][1]

        # all bones select

        # Bone constraints. Armature must be in pose mode.
        bpy.ops.object.mode_set(mode='POSE')

        bpy.ops.pose.select_all(action="SELECT")

        # Edit
        bpy.ops.object.editmode_toggle()

        if helicity == 'right':
            bpy.ops.armature.calculate_roll(type='GLOBAL_POS_Z')
        else:
            bpy.ops.armature.calculate_roll(type='GLOBAL_NEG_Z')
 
        # IK constraint
        cns = rig.pose.bones['y1a2'].constraints.new('IK')
        cns.name = 'Ik'
        cns.target = rig
        cns.subtarget = 'a2a1'
        cns.chain_count = 2
        cns.use_stretch = False

        bpy.ops.object.mode_set(mode='OBJECT')

    # Parent set disciple to master        
    def setParent(self, helicity, move, rig, disciple_loc, disciple_rot, disciple):

        bpy.ops.object.mode_set(mode='OBJECT')

        bpy.context.scene.frame_current = 0

        bpy.ops.object.select_all(action='DESELECT')
        rig.select_set(state=True)
        bpy.context.view_layer.objects.active = rig

        bpy.ops.object.editmode_toggle()

        parent_bone = 'b1y1' # choose the bone name which you want to be the parent

        rig.data.edit_bones.active = rig.data.edit_bones[parent_bone]

        bpy.ops.object.mode_set(mode='OBJECT')

        bpy.ops.object.select_all(action='DESELECT') #deselect all objects

        disciple.rig.select_set(state=True)

        rig.select_set(state=True)
        bpy.context.view_layer.objects.active = rig    #the active object will be the parent of all selected object

        bpy.ops.object.parent_set(type='BONE', keep_transform=True)

        bpy.ops.object.select_all(action='DESELECT') #deselect all objects

        # disciple position
        disciple.rig.location.x += disciple_loc[0]
        disciple.rig.location.y += disciple_loc[1]
        disciple.rig.location.z += disciple_loc[2]

        disciple.rig.rotation_euler = disciple_rot

    def configLink(self, A, J, helicity, rig, move, part):

        bpy.ops.object.mode_set(mode='OBJECT')
    
        Q = (0.18648+0.146446)*A
    #   Z = -Q*2
        Z = 0.0

        obj_joint = bpy.data.objects["joint.gold.000"].copy()
        obj_joint.location = (0.0, 0.0, -Q*3+Z)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "a2a1.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        obj_joint = bpy.data.objects["joint.silver.001"].copy()
        obj_joint.location = (0.0, 0.0, +Q+Z)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "y1a2.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        obj_joint = bpy.data.objects["joint.copper.y1o1"].copy()
        obj_joint.location = (0.0, 0.0, +Q*3+Z)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "y1o1.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        obj_joint = bpy.data.objects["joint.blue.001"].copy()
        obj_joint.location = (0.0, 0.0, -Q*2+Z)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "a1b1.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        n = 1

        # Pattern 2 of by
        obj_joint = bpy.data.objects["joint.green.001"].copy()
        obj_joint.location = (0.0, 0.0, -Q + Q*((n+1) % 2)*4 +Z)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "b"+str(n)+"y"+str(n)+".mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        # Pattern 2 of yy
        obj_joint = bpy.data.objects["joint.gold.00"+str(1 + (n+1) % 2)].copy()
        obj_joint.location = (0.0, 0.0, +Q*(1 - (n % 2))*2+Z)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "y"+str(n)+"y"+str(n+1)+".mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        for ob in data.collections['link'].objects:
            if "mesh" in ob.name:
                ob.select_set(state = True, view_layer = None)

        bpy.ops.object.make_single_user(type='SELECTED_OBJECTS', object=True, obdata=True, material=True, animation=True)
        bpy.context.scene.cursor.location = (0.0, 0.0, 0.0)
        bpy.ops.object.origin_set(type='ORIGIN_CURSOR')
        

class Arm(Formula):

    J = 7 #joint number

    # Overriding
    def __init__(self, P, A, move, part, helicity, start, end,
            disciple_loc, disciple_rot, disciple, disciple2):

        global interval
        global frame_start
        global frame_end

        self.interval = interval
        self.frame_start = frame_start
        self.frame_end = frame_end

        # pivot factor
        self.P = P

        # scale factor
        self.A = A 

        # name
        self.move = move

        # element
        self.part = part

        # element helicity
        self.helicity = helicity

        self.start = start
        self.end = end

        # disciple position
        self.disciple_loc = disciple_loc
        self.disciple_rot = disciple_rot

        # disciple
        self.disciple = disciple

        # disciple2
        self.disciple2 = disciple2

        # Create armature and object
        self.amt = bpy.data.armatures.new(move + '.' + part + '.' + helicity + '.data')
        self.rig = bpy.data.objects.new(move + '.' + part + '.' + helicity, self.amt)

        # Joints
        self.a = [0 for i in range(4)] # Joint α
        self.b = [0 for i in range(self.J)] # Joint β
        self.y = [0 for i in range(self.J)] # Joint γ
        self.o = [0 for i in range(self.J)] # Joint δ

        # Configuration Movement
        self.configMovement(self.P, self.A, self.J, self.a, self.b, self.y, self.o)

        # Construction Movement
        self.constructMovement(self.J, self.helicity, self.amt, self.rig, self.a, self.b, self.y, self.o)

        # Parent set disciple to master
        self.setParent(self.helicity, self.move, self.rig, self.disciple_loc, self.disciple_rot, self.disciple, self.disciple2)

        # Construction Rotation
        self.configRotation(self.rig, self.interval, self.frame_start, self.frame_end, self.start, self.end)

        # Configuration Linkage
        self.configLink(self.A*0.8779325, self.J, self.helicity, self.rig, self.move, self.part)

        # Construction Linkage
        self.constructLink(self.A*0.8779325, self.J, self.helicity, self.rig, self.move, self.part)

    # Overriding Configuration Movement
    def configMovement(self, P, A, J, a, b, y, o):

        a[1] = mathutils.Euler((P, A, 0.0), 'XYZ')
        print ("a1 =", a[1])

        a[2] = mathutils.Euler((A, -A, 0.0), 'XYZ')
        print ("a2 =", a[2])

        b[1] = mathutils.Euler((-A, A, 0.0), 'XYZ')
        print ("b1 =", b[1])

        o[1] = mathutils.Euler((A, A, 0.0), 'XYZ')
        print ("o1 =", o[1])

        B = A * 2 * sqrt (2)
        C = B + (B * sqrt (2))
        D = C * sqrt (2)
        E = C + D

        y[1] = mathutils.Euler((-A, -A, 0.0), 'XYZ')
        print ("y1 =", y[1])

        b[2] = mathutils.Euler((3*A, A, 0.0), 'XYZ')
        print ("b2 =", b[2])

        b[3] = mathutils.Euler(((1.45841/0.4)*A, (-5.17411/0.4)*A, 0.0), 'XYZ')
        print ("b3 =", b[3])
        
        b[4] = mathutils.Euler(((9.89715/0.4)*A, (-9.3493/0.4)*A, 0.0), 'XYZ')
        print ("b4 =", b[4])
        
        b[5] = mathutils.Euler(((7.83514/0.4)*A, (-11.3447/0.4)*A, 0.0), 'XYZ')
        print ("b5 =", b[5])

        o[2] = mathutils.Euler(((2.56784/0.4)*A, (1.11795/0.4)*A, 0.0), 'XYZ')
        print ("o2 =", o[2])
        
        o[3] = mathutils.Euler(((3.6051/0.4)*A, (-8.23989/0.4)*A, 0.0), 'XYZ')
        print ("o3 =", o[3])
        
        o[4] = mathutils.Euler(((7.94605/0.4)*A, (-10.7155/0.4)*A, 0.0), 'XYZ')
        print ("o4 =", o[4])
        
        o[5] = mathutils.Euler(((8.04983/0.4)*A, (-11.6512/0.4)*A, 0.0), 'XYZ')
        print ("o5 =", o[5])

        y[2] = mathutils.Euler((A, -A, 0.0), 'XYZ')
        print ("y2 =", y[2])

        y[3] = mathutils.Euler(((4.06465/0.4)*A, (-5.63365/0.4)*A, 0.0), 'XYZ')
        print ("y3 =", y[3])

        y[4] = mathutils.Euler(((7.72928/0.4)*A, (-10.8673/0.4)*A, 0.0), 'XYZ')
        print ("y4 =", y[4])
        
        y[5] = mathutils.Euler(((8.09577/0.4)*A, (-11.3906/0.4)*A, 0.0), 'XYZ')
        print ("y5 =", y[5])

        y[6] = mathutils.Euler(((8.46221/0.4)*A, (-11.914/0.4)*A, 0.0), 'XYZ')
        print ("y6 =", y[6])

    # Parent set disciple to master
    def setParent(self, helicity, move, rig, disciple_loc, disciple_rot, disciple, disciple2):

        bpy.ops.object.mode_set(mode='OBJECT')

        bpy.context.scene.frame_current = 0

        bpy.ops.object.select_all(action='DESELECT')
        rig.select_set(state=True)
        bpy.context.view_layer.objects.active = rig

        bpy.ops.object.editmode_toggle()

        parent_bone = 'b5y5' # choose the bone name which you want to be the parent

        rig.data.edit_bones.active = rig.data.edit_bones[parent_bone]

        bpy.ops.object.mode_set(mode='OBJECT')

        bpy.ops.object.select_all(action='DESELECT') #deselect all objects

        disciple.rig.select_set(state=True)

        rig.select_set(state=True)
        bpy.context.view_layer.objects.active = rig    #the active object will be the parent of all selected object

        bpy.ops.object.parent_set(type='BONE', keep_transform=True)

        bpy.ops.object.select_all(action='DESELECT') #deselect all objects

        # disciple position
        disciple.rig.location.x += disciple_loc[0]
        disciple.rig.location.y += disciple_loc[1]
        disciple.rig.location.z += disciple_loc[2]

        disciple.rig.rotation_euler = disciple_rot

        # disciple2
        bpy.ops.object.mode_set(mode='OBJECT')

        bpy.context.scene.frame_current = 0

        bpy.ops.object.select_all(action='DESELECT')
        rig.select_set(state=True)
        bpy.context.view_layer.objects.active = rig

        bpy.ops.object.editmode_toggle()

        parent_bone = 'b5y5' # choose the bone name which you want to be the parent

        rig.data.edit_bones.active = rig.data.edit_bones[parent_bone]

        bpy.ops.object.mode_set(mode='OBJECT')

        bpy.ops.object.select_all(action='DESELECT') #deselect all objects

        disciple2.rig.select_set(state=True)

        rig.select_set(state=True)
        bpy.context.view_layer.objects.active = rig    #the active object will be the parent of all selected object

        bpy.ops.object.parent_set(type='BONE', keep_transform=True)

        bpy.ops.object.select_all(action='DESELECT') #deselect all objects

        # disciple2 position
        disciple2.rig.location.x += disciple_loc[0]
        disciple2.rig.location.y += disciple_loc[1]
        disciple2.rig.location.z += disciple_loc[2]

        disciple2.rig.rotation_euler = disciple_rot

        
    def configLink(self, A, J, helicity, rig, move, part):

        bpy.ops.object.mode_set(mode='OBJECT')
    
        Q = (0.18648+0.146446)*A
    #   Z = -Q*2
        Z = 0.0

        obj_joint = bpy.data.objects["joint.gold.arm.a2a1"].copy()
        obj_joint.location = (0.0, 0.0, -Q*3+Z)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "a2a1.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        obj_joint = bpy.data.objects["joint.silver.001"].copy()
        obj_joint.location = (0.0, 0.0, +Q+Z)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "y1a2.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        obj_joint = bpy.data.objects["joint.copper.001"].copy()
        obj_joint.location = (0.0, 0.0, +Q*3+Z)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "a2o1.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        obj_joint = bpy.data.objects["joint.blue.001"].copy()
        obj_joint.location = (0.0, 0.0, -Q*2+Z)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "a1b1.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)


        for n in range(1, J - 1):

            if n <= (J-2):

                # Pattern 2 of by
                obj_joint = bpy.data.objects["joint.green.001"].copy()
                obj_joint.location = (0.0, 0.0, -Q + Q*((n+1) % 2)*4 +Z)
                obj_joint.scale = (A, A, A)
                obj_joint.name = "b"+str(n)+"y"+str(n)+".mesh." + move + '.' + part +'.' + helicity
                bpy.data.collections['link'].objects.link(obj_joint)

                # Pattern 2 of yy
                obj_joint = bpy.data.objects["joint.gold.00"+str(1 + (n+1) % 2)].copy()
                obj_joint.location = (0.0, 0.0, +Q*(1 - (n % 2))*2+Z)
                obj_joint.scale = (A, A, A)
                obj_joint.name = "y"+str(n)+"y"+str(n+1)+".mesh." + move + '.' + part +'.' + helicity
                bpy.data.collections['link'].objects.link(obj_joint)


            if n <= (J-3):

                # Pattern 1 of ob
                if n == 3:
                    obj_joint = bpy.data.objects["joint.blue.o3b4.arm"].copy()
                else:
                    obj_joint = bpy.data.objects["joint.blue.001"].copy()
                
                obj_joint.location = (0.0, 0.0, -Q*2 + Q*(n % 2)*6 +Z)
                obj_joint.scale = (A, A, A)
                obj_joint.name = "o"+str(n)+"b"+str(n+1)+".mesh." + move + '.' + part +'.' + helicity
                bpy.data.collections['link'].objects.link(obj_joint)

                # Pattern 2 of yo
                obj_joint = bpy.data.objects["joint.copper.001"].copy()
                obj_joint.location = (0.0, 0.0, -Q + Q*((n+1) % 2)*4 +Z)
                obj_joint.scale = (A, A, A)
                obj_joint.name = "y"+str(n+1)+"o"+str(n+1)+".mesh." + move + '.' + part +'.' + helicity
                bpy.data.collections['link'].objects.link(obj_joint)


        for ob in data.collections['link'].objects:
            if "mesh" in ob.name:
                ob.select_set(state = True, view_layer = None)

        bpy.ops.object.make_single_user(type='SELECTED_OBJECTS', object=True, obdata=True, material=True, animation=True)
        bpy.context.scene.cursor.location = (0.0, 0.0, 0.0)
        bpy.ops.object.origin_set(type='ORIGIN_CURSOR')



class LeftArm(Formula):

    J = 8 #joint number

    # Overriding
    def __init__(self, P, A, move, part, helicity, start, end):

        global interval
        global frame_start
        global frame_end

        self.interval = interval
        self.frame_start = frame_start
        self.frame_end = frame_end

        # pivot factor
        self.P = P

        # scale factor
        self.A = A 

        # name
        self.move = move

        # element
        self.part = part

        # element helicity
        self.helicity = helicity

        self.start = start
        self.end = end

        # Create armature and object
        self.amt = bpy.data.armatures.new(move + '.' + part + '.' + helicity + '.data')
        self.rig = bpy.data.objects.new(move + '.' + part + '.' + helicity, self.amt)

        # Joints
        # Joints α(n) -> a[n], β(n) -> b[n], γ(n) -> y[n], δ(n) -> o[n]
        self.a = [0 for i in range(self.J)] # Joint α
        self.b = [0 for i in range(self.J)] # Joint β
        self.y = [0 for i in range(self.J)] # Joint γ
        self.o = [0 for i in range(self.J)] # Joint δ

        # Joints ω(n) -> w[n]
        self.w = [0 for i in range(self.J)] # Joint ω

        # gimbal
        self.gimbal_b = [0 for i in range(self.J)] # Joint β
        self.gimbal_y = [0 for i in range(self.J)] # Joint γ

        # Configuration Movement
        self.configMovement(self.P, self.A, self.J,
            self.a, self.b, self.y, self.o,
            self.w,
            self.gimbal_b, self.gimbal_y)

        # Construction Movement
        self.constructMovement(self.J, self.helicity, self.part,
            self.amt, self.rig, 
            self.a, self.b, self.y, self.o,
            self.w,
            self.gimbal_b, self.gimbal_y)

        # Construction Rotation
#        self.configRotation(self.rig, self.interval, self.frame_start, self.frame_end, self.start, self.end)

        # Configuration Linkage
        self.configLink(self.A*0.8779325, self.J, self.helicity, self.rig, self.move, self.part)

        # Construction Linkage
        self.constructLink(self.A*0.8779325, self.J, self.helicity, self.rig, self.move, self.part)

    # Overriding Configuration Movement
    def configMovement(self, P, A, J, a, b, y, o, w, gimbal_b, gimbal_y):

        w[1] = mathutils.Euler((0.0, 0.0, 0.0), 'XYZ')
        print ("w1 =", w[1])

        o[1] = mathutils.Euler(((-0.2/0.4)*A, 0.0, 0.0), 'XYZ')
        print ("o1 =", o[1])

        b[2] = mathutils.Euler(((1.23875/0.4)*A, 0.0, 0.0), 'XYZ')
        print ("b2 =", b[2])

        y[3] = mathutils.Euler(((1.23875/0.4)*A, (-6.58841/0.4)*A, 0.0), 'XYZ')
        print ("y3 =", y[3])
        
        y[4] = mathutils.Euler(((1.23875/0.4)*A, (-11.8418/0.4)*A, (1.85078/0.4)*A), 'XYZ')
        print ("y4 =", y[4])

        y[5] = mathutils.Euler(((1.23875/0.4)*A, (-12.4749/0.4)*A, (1.85078/0.4)*A), 'XYZ')
        print ("y5 =", y[5])

        y[6] = mathutils.Euler(((16.1624/0.4)*A, (-6.81335/0.4)*A, (-16.0148/0.4)*A), 'XYZ')
        print ("y6 =", y[6])

        y[7] = mathutils.Euler(((16.1624/0.4)*A, (-6.81335/0.4)*A, (-17.2536/0.4)*A), 'XYZ')
        print ("y7 =", y[7])

        gimbal_b[2] = mathutils.Euler(((1.23875/0.4)*A, 0.0, 0.0), 'XYZ')
        print ("b2.gimbal =", gimbal_b[2])

        gimbal_y[3] = mathutils.Euler(((1.23875/0.4)*A, (-6.58841/0.4)*A, 0.0), 'XYZ')
        print ("y3.gimbal =", gimbal_y[3])
        

    def constructMovement(self, J, helicity, part,
        amt, rig, a, b, y, o, w, gimbal_b, gimbal_y):

        # Linkages
        aa = [[0 for i in range(4)] for j in range(4)] # Link α(i) - α(j)
        ab = [[0 for i in range(4)] for j in range(4)] # Link α(i) - β(j)
        ya = [[0 for i in range(4)] for j in range(4)] # Link γ(i) - α(j)
        yy = [[0 for i in range(self.J)] for j in range(self.J)] # Link γ(i) - γ(j)
        by = [[0 for i in range(self.J)] for j in range(self.J)] # Link β(i) - γ(j)
        yo = [[0 for i in range(self.J)] for j in range(self.J)] # Link γ(i) - δ(j)
        ob = [[0 for i in range(self.J)] for j in range(self.J)] # Link δ(i) - β(j)

        ow = [[0 for i in range(2)] for j in range(self.J)] # δ(j) - ω(j)

        gimbal_ob = [[0 for i in range(self.J)] for j in range(self.J)] # Link δ(i) - β(j)
        gimbal_by = [[0 for i in range(self.J)] for j in range(self.J)] # Link δ(i) - β(j)

        rig.location = mathutils.Euler((0.0, 0.0, 0.0), 'XYZ')
        rig.show_in_front = True
        amt.show_names = True
        amt.display_type = 'STICK'
#        amt.display_type = 'BBONE'

        # Link object to scene

        bpy.data.collections['movement'].objects.link(rig)
        bpy.context.view_layer.objects.active = rig
        bpy.context.view_layer.update()

        # Edit
        bpy.ops.object.editmode_toggle()
 
        ow[1][1] = amt.edit_bones.new('o1w1')
        ow[1][1].head = o[1]
        ow[1][1].tail = w[1]
#        ow[1][1].parent = yo[1][1]

        ob[1][2] = amt.edit_bones.new('o1b2')
        ob[1][2].head = w[1]
        ob[1][2].tail = b[2]
        ob[1][2].parent = ow[1][1]

        by[2][3] = amt.edit_bones.new('b2y3')
        by[2][3].head = b[2]
        by[2][3].tail = y[3]
        by[2][3].parent = ob[1][2]

        # gimbal
        gimbal_ob[1][2] = amt.edit_bones.new('o1b2.gimbal')
        gimbal_ob[1][2].head = w[1]
        gimbal_ob[1][2].tail = gimbal_b[2]
        gimbal_ob[1][2].parent = ow[1][1]

        gimbal_by[2][3] = amt.edit_bones.new('b2y3.gimbal')
        gimbal_by[2][3].head = gimbal_b[2]
        gimbal_by[2][3].tail = gimbal_y[3]
        gimbal_by[2][3].parent = gimbal_ob[1][2]
        # end

        yy[3][4] = amt.edit_bones.new('y3y4')
        yy[3][4].head = y[3]
        yy[3][4].tail = y[4]
        yy[3][4].parent = by[2][3]

        yy[4][5] = amt.edit_bones.new('y4y5')
        yy[4][5].head = y[4]
        yy[4][5].tail = y[5]
        yy[4][5].parent = yy[3][4]

        yy[6][7] = amt.edit_bones.new('y6y7')
        yy[6][7].head = y[6]
        yy[6][7].tail = y[7]
        yy[6][7].parent = ob[1][2]

        # all bones select

        # Bone constraints. Armature must be in pose mode.
        bpy.ops.object.mode_set(mode='POSE')

        bpy.ops.pose.select_all(action="SELECT")

        # Edit
        bpy.ops.object.editmode_toggle()

        if helicity == 'left ':
            bpy.ops.armature.calculate_roll(type='GLOBAL_POS_Z')
        else:
            bpy.ops.armature.calculate_roll(type='GLOBAL_NEG_Z')
              
        # Bone constraints. Armature must be in pose mode.
        bpy.ops.object.mode_set(mode='POSE')

        bpy.ops.pose.select_all(action="DESELECT")

        # Edit
        bpy.ops.object.editmode_toggle()

        amt.edit_bones["b2y3"].select = True
        amt.edit_bones["y3y4"].select = True
        amt.edit_bones["y4y5"].select = True

        bpy.ops.armature.calculate_roll(type='GLOBAL_POS_X')
 
        # IK constraint
        cns = rig.pose.bones['b2y3.gimbal'].constraints.new('IK')
        cns.name = 'Ik'
        cns.target = rig
        cns.subtarget = 'y3y4'
        cns.pole_target = rig
        cns.pole_subtarget = 'b2y3'
        cns.pole_angle = math.radians(0)

#        if part == 'leg-left':
#            cns.pole_angle = math.radians(0)
#        else:
#            cns.pole_angle = math.radians(180)
            
        cns.iterations = 500
        cns.chain_count = 2
        cns.use_stretch = False

        bpy.ops.object.mode_set(mode='OBJECT')

    def configLink(self, A, J, helicity, rig, move, part):

        bpy.ops.object.mode_set(mode='OBJECT')
    
        Q = (0.18648+0.146446)*A
    #   Z = -Q*2
        Z = 0.0

        n = 1

        obj_joint = bpy.data.objects["joint.gold.A"].copy()
        obj_joint.location = (0.0, 0.0, 0.0)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "o1w1.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        obj_joint = bpy.data.objects["joint.copper.A"].copy()
        obj_joint.location = (0.0, 0.0, 0.0)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "o1b2.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        obj_joint = bpy.data.objects["joint.blue.B"].copy()
        obj_joint.location = (0.0, 0.0, 0.0)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "b2y3.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        obj_joint = bpy.data.objects["joint.copper.g1.y.B"].copy()
        obj_joint.location = (0.0, 0.0, 0.0)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "o1b2.gimbal.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        obj_joint = bpy.data.objects["joint.blue.g1.z.B"].copy()
        obj_joint.location = (0.0, 0.0, 0.0)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "b2y3.gimbal.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        obj_joint = bpy.data.objects["joint.green.001"].copy()
        obj_joint.location = (0.0, 0.0, Q +Z)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "y3y4.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)
        
        obj_joint = bpy.data.objects["joint.gold.001"].copy()
        obj_joint.location = (0.0, 0.0, 0.0)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "y4y5.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        obj_joint = bpy.data.objects["joint.cursor"].copy()
        obj_joint.location = (0.0, 0.0, 0.0)
        obj_joint.scale = (A, A, A)
        obj_joint.name = "y6y7.mesh." + move + '.' + part +'.' + helicity
        bpy.data.collections['link'].objects.link(obj_joint)

        for ob in data.collections['link'].objects:
            if "mesh" in ob.name:
                ob.select_set(state = True, view_layer = None)

        bpy.ops.object.make_single_user(type='SELECTED_OBJECTS', object=True, obdata=True, material=True, animation=True)
        bpy.context.scene.cursor.location = (0.0, 0.0, 0.0)
        bpy.ops.object.origin_set(type='ORIGIN_CURSOR')


class RightArm(LeftArm):

    J = 8 #joint number

    # Overriding Configuration Movement
    def configMovement(self, P, A, J, a, b, y, o, w, gimbal_b, gimbal_y):

        w[1] = mathutils.Euler((0.0, 0.0, 0.0), 'XYZ')
        print ("w1 =", w[1])

        o[1] = mathutils.Euler(((-0.2/0.4)*A, 0.0, 0.0), 'XYZ')
        print ("o1 =", o[1])

        b[2] = mathutils.Euler(((1.23875/0.4)*A, 0.0, 0.0), 'XYZ')
        print ("b2 =", b[2])

        y[3] = mathutils.Euler(((1.23875/0.4)*A, (-6.58841/0.4)*A, 0.0), 'XYZ')
        print ("y3 =", y[3])
        
        y[4] = mathutils.Euler(((1.23875/0.4)*A, (-11.8418/0.4)*A, (1.85078/0.4)*A), 'XYZ')
        print ("y4 =", y[4])

        y[5] = mathutils.Euler(((1.23875/0.4)*A, (-12.4749/0.4)*A, (1.85078/0.4)*A), 'XYZ')
        print ("y5 =", y[5])

        y[6] = mathutils.Euler(((28.6854/0.4)*A, (-15.175/0.4)*A, (10.2097/0.4)*A), 'XYZ')
        print ("y6 =", y[6])

        y[7] = mathutils.Euler(((28.6854/0.4)*A, (-15.175/0.4)*A, (8.97093/0.4)*A), 'XYZ')
        print ("y7 =", y[7])

        gimbal_b[2] = mathutils.Euler(((1.23875/0.4)*A, 0.0, 0.0), 'XYZ')
        print ("b2.gimbal =", gimbal_b[2])

        gimbal_y[3] = mathutils.Euler(((1.23875/0.4)*A, (-6.58841/0.4)*A, 0.0), 'XYZ')
        print ("y3.gimbal =", gimbal_y[3])
        

def formula():

# pivot factor
    P = 0

# scale factor
    A = 1
    
# joint number
    J = 6
    
# name
    move = 'formula'

# element
    part = 'universe'

# left or right
    helicity = 'left'

    start = 0
    end = start+360

    formula = Formula(P, A, J, move, part, helicity, start, end)


def hands():

# name
    move = 'swing'

    # scale factor
    A = 0.107

    # pivot factor
    P = -0.048266

# config nonlocal
    global middle_left
    global middle_right

# finger element
    part = 'middle-left'

# phalanx length
    y2 = mathutils.Euler((1.427, -1.08668, 0.0), 'XYZ')
    y3 = mathutils.Euler((2.15534, -1.56395, 0.0), 'XYZ')
    y4 = mathutils.Euler((2.67012, -1.90121, 0.0), 'XYZ')
    y5 = mathutils.Euler((2.90459, -2.05473, 0.0), 'XYZ')

# left finger element
    helicity = 'left'

    start = 196
    end = start+0

    middle_left = Finger(P, A, move, part, helicity, start, end, y2, y3, y4, y5)
    
    middle_left.rig.location = (0.0, 0.0, 0.0)
    middle_left.rig.rotation_euler = mathutils.Euler((math.radians(0), math.radians(0), math.radians(0)), 'XYZ')

# finger element
    part = 'middle-right'

# right finger element
    helicity = 'right'

    start = 112
    end = start+0

    middle_right = Finger(P, A, move, part, helicity, start, end, y2, y3, y4, y5)    

    middle_right.rig.location = (0.0, 0.0, 0.0)
    middle_right.rig.rotation_euler = mathutils.Euler((math.radians(180-0), math.radians(0), math.radians(0)), 'XYZ')


# finger element
    part = 'ring-left'

    y2 = mathutils.Euler((1.36978, -1.04933, 0.0), 'XYZ')
    y3 = mathutils.Euler((2.16696, -1.57161, 0.0), 'XYZ')
    y4 = mathutils.Euler((2.63809, -1.8803, 0.0), 'XYZ')
    y5 = mathutils.Euler((2.87256, -2.03382, 0.0), 'XYZ')

# left finger element
    helicity = 'left'

    start = 222
    end = start+0

    ring_left = Finger(P, A, move, part, helicity, start, end, y2, y3, y4, y5)

    ring_left.rig.location = (-0.010689, 0.001192, 0.241051)
    ring_left.rig.rotation_euler = mathutils.Euler((math.radians(-5.10153), math.radians(-1.70737), math.radians(0.02464)), 'XYZ')

# finger element
    part = 'ring-right'

# right finger element
    helicity = 'right'

    start = 126
    end = start-0

    ring_right = Finger(P, A, move, part, helicity, start, end, y2, y3, y4, y5)    

    ring_right.rig.location = (-0.010689, -0.001192, 0.241051)
    ring_right.rig.rotation_euler = mathutils.Euler((math.radians(180+5.10153), math.radians(-1.70737), math.radians(-0.02464)), 'XYZ')


# finger element
    part = 'little-left'
    
    y2 = mathutils.Euler((1.45986, -1.08525, 0.0), 'XYZ')
    y3 = mathutils.Euler((2.10861, -1.50077, 0.0), 'XYZ')
    y4 = mathutils.Euler((2.5324, -1.77219, 0.0), 'XYZ')
    y5 = mathutils.Euler((2.72302, -1.89418, 0.0), 'XYZ')

# left finger element
    helicity = 'left'

    start = 235
    end = start+0

    little_left = Finger(P, A, move, part, helicity, start, end, y2, y3, y4, y5)

    little_left.rig.location = (-0.020568, 0.002289, 0.463882)
    little_left.rig.rotation_euler = mathutils.Euler((math.radians(-10.1646), math.radians(-2.09755), math.radians(-0.518101)), 'XYZ')

# finger element
    part = 'little-right'

# right finger element
    helicity = 'right'

    start = 117
    end = start-0

    little_right = Finger(P, A, move, part, helicity, start, end, y2, y3, y4, y5)

    little_right.rig.location = (-0.020568, -0.002289, 0.463882)
    little_right.rig.rotation_euler = mathutils.Euler((math.radians(180+10.1646), math.radians(-2.09755), math.radians(0.518101)), 'XYZ')


# finger element
    part = 'index-left'

    y2 = mathutils.Euler((1.36561, -1.0465, 0.0), 'XYZ')
    y3 = mathutils.Euler((2.0559, -1.49887, 0.0), 'XYZ')
    y4 = mathutils.Euler((2.52701, -1.80756, 0.0), 'XYZ')
    y5 = mathutils.Euler((2.76149, -1.96108, 0.0), 'XYZ')

# left finger element
    helicity = 'left'

    start = 165
    end = start+0

    index_left = Finger(P, A, move, part, helicity, start, end, y2, y3, y4, y5)

    index_left.rig.location = (0.012703, -0.00141, -0.286505)
    index_left.rig.rotation_euler = mathutils.Euler((math.radians(2.53073), math.radians(2.85122), math.radians(0.320067)), 'XYZ')

# finger element
    part = 'index-right'

# right finger element
    helicity = 'right'

    start = 187
    end = start-0

    index_right = Finger(P, A, move, part, helicity, start, end, y2, y3, y4, y5)

    index_right.rig.location = (0.012703, 0.00141, -0.286505)
    index_right.rig.rotation_euler = mathutils.Euler((math.radians(180-2.53073), math.radians(2.85122), math.radians(-0.320067)), 'XYZ')


# finger element
    part = 'thumb-left'

    P = -0.075869 #pivot factor

    y2 = mathutils.Euler((0.265988, -0.219792, 0.0), 'XYZ')
    y3 = mathutils.Euler((1.0999, -0.768173, 0.0), 'XYZ')
    y4 = mathutils.Euler((1.71494, -1.17263, 0.0), 'XYZ')
    y5 = mathutils.Euler((1.97601, -1.3443, 0.0), 'XYZ')

# left finger element
    helicity = 'left'

    start = 226
    end = start+0

    thumb_left = Finger(P, A, move, part, helicity, start, end, y2, y3, y4, y5)

    thumb_left.rig.location = (0.009956, -0.090396, -0.3247)
    thumb_left.rig.rotation_euler = mathutils.Euler((math.radians(87.8968), math.radians(-3.16487), math.radians(-23.1096)), 'XYZ')

# finger element
    part = 'thumb-right'

# right finger element
    helicity = 'right'

    start = -206
    end = start+0

    thumb_right = Finger(P, A, move, part, helicity, start, end, y2, y3, y4, y5)

    thumb_right.rig.location = (0.009956, 0.090396, -0.3247)
    thumb_right.rig.rotation_euler = mathutils.Euler((math.radians(180-87.8968), math.radians(-3.16487), math.radians(23.1096)), 'XYZ')


# Parent set four fingers to middle finger
    bpy.ops.object.mode_set(mode='OBJECT')

    bpy.context.scene.frame_current = 0

# left hand
    bpy.ops.object.select_all(action='DESELECT')
    middle_left.rig.select_set(state=True)
    bpy.context.view_layer.objects.active = middle_left.rig

    bpy.ops.object.editmode_toggle()

    parent_bone = 'a2a1' # choose the bone name which you want to be the parent

    middle_left.rig.data.edit_bones.active = middle_left.rig.data.edit_bones[parent_bone]

    bpy.ops.object.mode_set(mode='OBJECT')

    bpy.ops.object.select_all(action='DESELECT') #deselect all objects
    ring_left.rig.select_set(state=True)
    little_left.rig.select_set(state=True)
    index_left.rig.select_set(state=True)
    thumb_left.rig.select_set(state=True)
    middle_left.rig.select_set(state=True)
    bpy.context.view_layer.objects.active = middle_left.rig    #the active object will be the parent of all selected object

    bpy.ops.object.parent_set(type='BONE', keep_transform=True)

# right hand
    bpy.ops.object.select_all(action='DESELECT') #deselect all objects
    middle_right.rig.select_set(state=True)
    bpy.context.view_layer.objects.active = middle_right.rig

    bpy.ops.object.editmode_toggle()

    parent_bone = 'a2a1' # choose the bone name which you want to be the parent

    middle_right.rig.data.edit_bones.active = middle_right.rig.data.edit_bones[parent_bone]

    bpy.ops.object.mode_set(mode='OBJECT')

    bpy.ops.object.select_all(action='DESELECT') #deselect all objects
    ring_right.rig.select_set(state=True)
    little_right.rig.select_set(state=True)
    index_right.rig.select_set(state=True)
    thumb_right.rig.select_set(state=True)
    middle_right.rig.select_set(state=True)
    bpy.context.view_layer.objects.active = middle_right.rig    #the active object will be the parent of all selected object

    bpy.ops.object.parent_set(type='BONE', keep_transform=True)

    bpy.ops.object.select_all(action='DESELECT') #deselect all objects


def wrists():
    
# scale factor
    A = 0.351
    
# pivot factor
    P = 0

# name
    move = 'swing'


# wrist element
    part = 'wrist-left'

# helicity
    helicity = 'right'

    start = 0
    end = start-1440

    fingers_loc = ((-0.998894/0.351)*A, (-0.000381/0.351)*A, (-0.349921/0.351)*A)
    fingers_rot = mathutils.Euler((math.radians(302.398), math.radians(10.1313), math.radians(688.017)), 'XYZ')

    global middle_left
    middle_finger = middle_left
    
    global wrist_left
    wrist_left = Wrist(P, A, move, part, helicity, start, end, fingers_loc, fingers_rot, middle_finger)


# right wrist element
    part = 'wrist-right'

# helicity
    helicity = 'right'

    start = 0
    end = start-1440

    fingers_loc = ((-0.436933/0.351)*A, (-0.737941/0.351)*A, (-1.12234/0.351)*A)
    fingers_rot = mathutils.Euler((math.radians(-2.7126), math.radians(-114.769), math.radians(-317.672)), 'XYZ')

    global middle_right
    middle_finger = middle_right
    
    global wrist_right
    wrist_right = Wrist(P, A, move, part, helicity, start, end, fingers_loc, fingers_rot, middle_finger)


def arms():

# scale factor
    A = 0.4

# pivot factor
    P = 0.0

# name
    move = 'swing'

# arm element
    part = 'center-arm'

# left arm element
    helicity = 'right'

    start = -180
    end = start+1440

    wrist_loc = ((8.1191/0.4)*A, (-10.9722/0.4)*A, (0.142473/0.4)*A)
    wrist_rot = mathutils.Euler((math.radians(16.8768), math.radians(208.612), math.radians(29.4008)), 'XYZ')

    global wrist_left
    
    global wrist_right

    global arm_center
    arm_center = Arm(P, A, move, part, helicity, start, end, wrist_loc, wrist_rot, wrist_left, wrist_right)
#    arm_center = Arm2(P, A, move, part, helicity, start, end)

    arm_loc = ((7.24089/0.421838)*A, (1.945975/0.421838)*A, (6.33985/0.421838)*A)
    arm_rot = mathutils.Euler((math.radians(0.0), math.radians(180.0), math.radians(-37.074)), 'XYZ')

    # position
    arm_center.rig.location.x += arm_loc[0]
    arm_center.rig.location.y += arm_loc[1]
    arm_center.rig.location.z += arm_loc[2]

    arm_center.rig.rotation_euler = arm_rot

# element
    part = 'left-arm'

# left or right
    helicity = 'right'

    start = -2679.14
    end = start+360

    global arm_left
    arm_left = LeftArm(P, A, move, part, helicity, start, end)

# element
    part = 'right-arm'

    helicity = 'right'

    global arm_right
    arm_right = RightArm(P, A, move, part, helicity, start, end)


    global middle_left
    
    cns = arm_left.rig.pose.bones['y3y4'].constraints.new('IK')
    cns.name = 'Ik'
    cns.target = middle_left.rig
    cns.subtarget = 'b1y1'
    cns.pole_target = arm_left.rig
    cns.pole_subtarget = 'y6y7'
    cns.pole_angle = math.radians(180)
    cns.iterations = 500
    cns.chain_count = 2
    cns.use_stretch = False

    cns = arm_left.rig.pose.bones['y4y5'].constraints.new('DAMPED_TRACK')
    cns.name = 'Damped Track'
    cns.target = middle_left.rig
    cns.subtarget = 'a2a1'
    
    global middle_right
    
    cns = arm_right.rig.pose.bones['y3y4'].constraints.new('IK')
    cns.name = 'Ik'
    cns.target = middle_right.rig
    cns.subtarget = 'b1y1'
    cns.pole_target = arm_right.rig
    cns.pole_subtarget = 'y6y7'
    cns.pole_angle = math.radians(180)
    cns.iterations = 500
    cns.chain_count = 2
    cns.use_stretch = False

    cns = arm_right.rig.pose.bones['y4y5'].constraints.new('DAMPED_TRACK')
    cns.name = 'Damped Track'
    cns.target = middle_right.rig
    cns.subtarget = 'a2a1'
    
    arm_loc = ((3.664601/0.421838)*A, (3.02509/0.421838)*A, (8.33447/0.421838)*A)
    arm_rot = mathutils.Euler((math.radians(-13.9201), math.radians(185.688), math.radians(58.3892)), 'XYZ')

    # position
    arm_left.rig.location.x += arm_loc[0]
    arm_left.rig.location.y += arm_loc[1]
    arm_left.rig.location.z += arm_loc[2]

    arm_left.rig.rotation_euler = arm_rot
    
    arm_loc = ((3.665264/0.421838)*A, (3.023535/0.421838)*A, (3.689461/0.421838)*A)
    arm_rot = mathutils.Euler((math.radians(13.9338), math.radians(174.433), math.radians(58.3589)), 'XYZ')

    # position
    arm_right.rig.location.x += arm_loc[0]
    arm_right.rig.location.y += arm_loc[1]
    arm_right.rig.location.z += arm_loc[2]

    arm_right.rig.rotation_euler = arm_rot


def main(origin):
    
    # create new collection
    newCol = bpy.data.collections.new('movement')
    # link the newCol to the scene
    bpy.context.scene.collection.children.link(newCol)

    newCol = bpy.data.collections.new('link')
    bpy.context.scene.collection.children.link(newCol)

    global interval
    global frame_start
    global frame_end

    frame_start = 0
    frame_end = 240

    interval = frame_end - frame_start

#    formula()
    hands()
    wrists()
    arms()

if __name__ == "__main__":
    # renaming of corrada objects
#    for ob in context.collection.objects:
#        if "joint_" in ob.name:
#            ob.name = ob.name.replace("_", ".")
            
    main((0.0, 0.0, 0.0)) 
